export interface VersionEntry {
  version: string;
  description: string;
  isForkStart?: boolean;
}

export const VERSIONS: VersionEntry[] = [
  { version: '1.16.1', description: 'Fix: Changelog header stays fixed when scrolling. Renamed to "Changelog".' },
  { version: '1.16.0', description: 'Version data now in single source of truth - top bar and changelog always in sync.' },
  { version: '1.15.0', description: 'Top bar has distinct background color. Title updated to "Andy\'s Fork" branding. Changelog now follows SemVer.' },
  { version: '1.14.0', description: 'Attributes panel now displays column headers and additional stats (Starting Value, Aptitude, Gain Multiplier).' },
  { version: '1.13.0', description: 'Add Easy Mode banner and indicator to achievements panel.' },
  { version: '1.12.1', description: 'Fix: Use easyModeEver flag for achievement hints.' },
  { version: '1.12.0', description: 'Enhanced achievements panel with progress tracking and locked/unlocked sections.' },
  { version: '1.11.0', description: 'Add quality tier badges to inventory items.' },
  { version: '1.10.0', description: 'Enriched item tooltips with detailed effects.' },
  { version: '1.9.0', description: 'UI improvements and docs cleanup.' },
  { version: '1.8.0', description: 'Redesign farm panel with batch cards and shared tooltips.' },
  { version: '1.7.0', description: 'Improve Home panel tooltips and add clear field button.' },
  { version: '1.6.0', description: 'Add base lifespan tooltip and improve time formatting.' },
  { version: '1.5.0', description: 'Redesign Health panel with flexbox layout and lifespan info display.' },
  { version: '1.4.0', description: 'Multiple workbench slots with per-slot ownership and UI improvements.' },
  { version: '1.3.0', description: 'UI improvements for Home, Equipment, and Health panels.' },
  { version: '1.2.6', description: 'Map existing codebase (documentation).' },
  { version: '1.2.5', description: 'Bug fixes for pet options. Some performance optimizations and a new version of the code framework (Angular v18).', isForkStart: true },
  { version: '1.2.4', description: 'Bug fix for pet training not leveling up pets.' },
  { version: '1.2.3', description: 'Icons for items and equipment (some old items and equipment from before the update won\'t show the icons). New selected item view in the Inventory Panel. Pets got their own panel separate from followers. Autopill and autopotion can now be turned off in the options. Some internal code cleanup/changes to comply with modern code framework standards. Bug fixes.' },
  { version: '1.2.2', description: 'Panel layouts can now be imported and exported from the options panel. Bugfixes for scrollbars on some panels. Clicking info or schedule on an activity no longer also clicks the activity. Attribute panel layout update.' },
  { version: '1.2.1', description: 'Equipment panel will now show up if you have any equipment. Bug fixes for locked panels checkbox.' },
  { version: '1.2.0', description: 'New user interface with movable and resizable game panels that should work on tablets and phones. Pictures of monsters and activities. Changes to activity panel (just click the activity to do it once). Some panels now only unlock once they are needed. Some new achievements for unlocking panels. Portals panel for moving between hell dimensions. Bug fixes. Added classic version for people who liked the game better the old way (just add "classic" to the game URL).' },
  { version: '1.1.4', description: 'Added animated text for attributes and money changes and an option to turn them off. Fixed some performance issues and typos. Fixed infinite hell money bug. The mountain of knives in hell should no longer be unsolvable for some cultivators.' },
  { version: '1.1.3', description: 'Fixed items being sold in hell when autobalanced. Activities Panel now shows activities in a grid, allowing more activities to show on the screen at a time (descriptions are now in a popup panel). New buttons on activities to let you do them right now without scheduling them.' },
  { version: '1.1.2', description: 'Background music is now available in the options panel, this can also improve performance when the game\'s tab is not active on some browsers (even if the tab is muted). A new achievement makes it easier to get regular daily yields from your farm fields. Some logging and preformance improvements for cultivators experiencing time at very high rates.' },
  { version: '1.1.1', description: 'Your spiritual projection can no longer do activities you can\'t do yourself. Reduced the grind required on some hells. Added a Dismiss All Followers button. Bug fixes.' },
  { version: '1.1.0', description: 'Hell Expansion for advanced cultivators who are ready to move beyond simple immortality. Bug fixes.' },
  { version: '1.0.63', description: 'Grandmother still loves you even when you are very powerful. Additional accessibility support. Bug fixes' },
  { version: '1.0.62', description: 'Screen readers can now read the game\'s icon buttons. Core Cultivation will not show up until mana is unlocked. Balancing Chi is now available earlier but will not work at full strength until mana is unlocked. New achievements. Bug fixes.' },
  { version: '1.0.61', description: 'A new achievement for managing your followers. Immortality races Season 1 (see the Discord). Bug fixes.' },
  { version: '1.0.60', description: 'Equipment and Home panels can now be collapsed. Bug fixes.' },
  { version: '1.0.59', description: 'Life summary panel. Tips are available for cultivators who don\'t want to figure things out on their own. Automated merging is easier to achieve. Low level crafting produces better items. Balance changes to equipment and boss fights. Game speed hotkeys changed. Bug fixes.' },
  { version: '1.0.58', description: 'Tuned equipment degradation down. Equipment should now reach equilibrium between damage and improvement at higher points.' },
  { version: '1.0.57', description: 'Fix for wooden weapons not getting proper benefit from weaponsmiths.' },
  { version: '1.0.56', description: 'New tooltip system. Notification for offline tick gains. Minor changes to import/export functions. Equipment damage system changed. Hotkeys 0-5 for game speeds. Activities you can\'t do now show as disabled instead of disappearing. Notification popups. Bug fixes.' },
  { version: '1.0.55', description: 'Monsters have started dropping better hides. Inventory sorting. A new activity. More options panel options. You can import and export save files instead of text blocks. Bug fixes.' },
  { version: '1.0.54', description: 'Preformance improvements to allow experienced cultivators fly through the centuries. A new activity. Bug fixes.' },
  { version: '1.0.53', description: 'You might be more powerful now. Certain enemies might also be. More powerful herbs have been spotted in the wilds. New crafting options. UI improvements and bug fixes.' },
  { version: '1.0.52', description: 'Even more Bloodline ascensions are now available. New activities. Bug fixes.' },
  { version: '1.0.51', description: 'A Statistics Panel is now available to show cultivators some information about what they have done. Additional Bloodline ascensions are now available. A late game boss is stronger but now has less health to make that fight less of a grind. Cultivators with the right knowledge can automatically rest instead of becoming exhausted. Some additional game options are available. Balance changes and bug fixes.' },
  { version: '1.0.50', description: 'An easy mode is available to cultivators who think the game is too hard. New achievements and manuals. New activities for magically empowered seekers of immortality. UI improvements. Bug fixes and balance improvements.' },
  { version: '1.0.49', description: 'Pause before death is available if you know the right secrets. Improvements to followers. Better game performance.' },
  { version: '1.0.48', description: 'Better follower management. Item names stay more consistent when merged and upgraded. Balance and bug fixes.' },
  { version: '1.0.47', description: 'Better inventory slots that don\'t jiggle around. Auto-sell and auto-use can now reserve some of the items (set value in the options panel). Bug and balance fixes.' },
  { version: '1.0.46', description: 'Condensing your Soul Core now provides greater benefits.' },
  { version: '1.0.45', description: 'A powerful new pill can now be created by aspiring immortals who have mastered many jobs.' },
  { version: '1.0.44', description: 'Autobuy options are now configurable if you have found the secret knowledge needed.' },
  { version: '1.0.43', description: 'When the game is paused you can advance a day with the Enter key. Time now moves faster the older you are starting at 5,000 years old. Base lifespan now increases based on total days lived, not number of lives lived. Balance changes to attributes and aptitudes.' },
  { version: '1.0.42', description: 'Gaining large numbers of items at once is now much more efficient, so having obscenely huge farms no longer breaks the game.' },
  { version: '1.0.41', description: 'Panel size fixes. Bloodline ascension rank 5. Fixed log line duplication bug. Pause on death should no longer allow extra days to pass before pausing.' },
  { version: '1.0.40', description: 'Changed the way damage and armor work. Late-game fights should now be more epic and interesting.' },
  { version: '1.0.39', description: 'Better descriptions for resting activities. Shift-click activities to load them onto the schedule 10 at a time. Canopy beds give more health.' },
  { version: '1.0.38', description: 'Better performance for aspiring immortals who want to buy vast tracts of land.' },
  { version: '1.0.37', description: 'New status bars that show values on non-chrome browsers.' },
  { version: '1.0.36', description: 'You can now choose how much money to reserve when doing automatic purchases.' },
  { version: '1.0.35', description: 'The log panel can now be resized by sliding the slider up and down. The Ascension Techniques panel stays unlocked once unlocked. Old junky gems can now be easily removed if you know how.' },
  { version: '1.0.34', description: 'Style fix, clear schedule button, and auto-equip can now be turned off in the options.' },
  { version: '1.0.33', description: 'Some styling improvements and a fix to very late game reward loot.' },
  { version: '1.0.32', description: 'Automerging will now upgrade equipped weapons and armor if all merge manuals have been achieved and purchased.' },
  { version: '1.0.31', description: 'Some balance changes.' },
  { version: '1.0.30', description: 'A certain impossible task is now slightly less impossible.' },
  { version: '1.0.29', description: 'Silly levels that stamina could reach are now slightly less silly. Pausing the game banks time ticks.' },
  { version: '1.0.28', description: 'Improvements to automatic home purchasing.' },
  { version: '1.0.27', description: 'You can now save and load an activity schedule.' },
  { version: '1.0.26', description: 'Fixed a bug with activities incorrectly being removed from the schedule on reincarnation.' },
  { version: '1.0.25', description: 'New activities and activity upgrades now get log entries. Armor now degrades when attacked.' },
  { version: '1.0.24', description: 'Bug fix for aspiring immortals who got tangled up while trying to swim to the bottom of the ocean.' },
  { version: '1.0.23', description: 'Bug fix for aspiring immortals who achieved infinite wealth. Money is now capped at an amount that is plenty for everything but doesn\'t break your computer.' },
  { version: '1.0.22', description: 'Leatherworking and Woodworking now have master ranks. You can now see how much money you made on each job the last time you did it. Better logs can now be chopped.' },
  { version: '1.0.21', description: 'Followers can now be trained to be more powerful and can be automatically dismissed by job.' },
  { version: '1.0.20', description: 'Added Discord link.' },
  { version: '1.0.19', description: 'Added changelog.' },
  { version: '1.0.18', description: 'New follower types are now available.' },
  { version: '1.0.17', description: 'Crafting log entries can now be filtered out.' },
  { version: '1.0.16', description: 'Added tutorial help button.' },
  { version: '1.0.15', description: 'Christian B created and launched the game.' },
];

export const CURRENT_VERSION = VERSIONS[0].version;
