export const JoinTheGodsText =
  'You take to the skies, flying far above the human realms. You soar over the Kunlun Mountains, past Mount Tai, and beyond the Jade Mountains until the earth falls away to the Great Sea.\n\nMount Penglai emerges from the mist, a lone pillar rising to pierce the very vault of heaven. Its pure white slopes are crowned with palaces of silver and gold, nestled among trees that bear glittering jewels instead of leaves.\n\nYour gaze wanders to the side where you notice an orchard of trees that grow the most delectable fruits you\'ve ever seen: mythical fruits that grant perfect health and eternal youth to whoever eats them.\n\nYou look at them, then back at the memory of your own harvest as a familiar weight presses down on your mind. Your own peaches never looked as divine, no matter how hard you worked your land to cultivate them.\n\n' +
  '<img src="assets/images/activities/joinTheGods1.png" alt="The golden palace of Mount Penglai">\n\n' +
  "You push down your feelings of inadequacy and press onward toward the gates of the Golden Palace. You are an Immortal now, after all; you have earned your place here. As you stride into the vast courtyard, you find an assembly of gods there, seated on golden thrones. The Eight Immortals are there, each holding their artifact of power as they laugh raucously at one another's jokes. Nuwa and Fuxi, the great ancestors of humanity, sit idly chatting as the Queen Mother of the West exchanges quiet words with Caishen in his most exquisite of all silks. In the center of them all, Shangti, the Jade Emperor himself, sits upon his elevated throne. As you approach, he claps his hands for silence. You were clearly expected.\n\n" +
  '"Ah, the young upstart who has caused so much trouble in the mortal realm has finally arrived!" said the Jade Emperor.\n\n' +
  'The other gods greet you with nothing but steely stares. You nod in acknowledgement and take another step toward the thrones. You notice that one of them off to the side is empty. A place for you, perhaps?\n\n' +
  '"I suppose you feel you deserve a place here with us now, do you?" the Jade Emperor continues. "Fight a few monsters, improve yourself a bit, conquer a few of your fellow mortals, and suddenly you\'ve earned the right to call yourself a god, eh?"\n\n' +
  'You nod again; your long periods of cultivation have made you a bit autistic, and you miss the mockery in the Jade Emperor\'s words. You prepare to recount the long journey of cultivation and devotion that led you to this point when a towering figure to your right cuts you off before you can begin.\n\n' +
  '"Nonsense!" an ominous voice thunders with authority. "This upstart destroyed one of my best servants and committed uncountable sins for which no price has been paid."\n\n' +
  '"And what would you suggest be done with this new Immortal, Lord Yama?" the Jade Emperor asks. "This one possesses the requisite power and a certain... stubbornness of spirit. One way or another, sooner or later, that empty throne will be filled."\n\n' +
  '"Let this one come to my domain," Lord Yama declares. "The Eighteen Hells will show whether they have the character fitting for a throne in the Penglai Palace."\n\n' +
  'The other gods look back and forth at one another for a moment.\n\n"That seems only fair," one of them says, a short, hairy man with horns growing from his head. "This new Immortal still has much to learn, and much to atone for. Why, they don\'t even understand simple concepts like balancing their Yin and Yang. They may be ready one day for this company, but a few millennia in Yama\'s realm will do them good."\n\n' +
  'The other gods murmur and nod in agreement.\n\n"Your words are wise as always, Pan Gu," the Jade Emperor says, rising to his feet. "Let this one be cast down to the Eighteen Hells. If they can master Yin and Yang and prove their worth through the trials of Yama\'s realm, we will welcome them as part of our Celestial Court."\n\n' +
  'Before you can say a word of protest, the Jade Emperor waves one hand and you find yourself in a vast, bare, circular stone room. The walls are broken by eighteen open gates, each one leading to a different world of pain and suffering.\n\n' +
  'Your body aches, but your goal is clear: Pass the trials of the Eighteen Hells and prove your worth to the gods.';
